### ISSUE TITLE
Handle daily barcode upload 

### ISSUE THREAD

**Issue by ckmah** [shassathe/covid_qPCR_test#12]
@shassathe elaborate

**Comment by noor01** [comment]
Would this be good as another daily cron job since it's a one time regularly scheduled thing?

**Comment by shassathe** [comment]
Nah, cant be a cron job since Mark will probably receive a file by email.  So I'll just have an upload file button and parse the file that gets uploaded.

**Comment by shassathe** [comment]
Added text file upload. File must contain 1 barcode per line. App will parse file and create records in the DB
