### ISSUE TITLE
Color Tab in Update Existing Records template

### ISSUE THREAD

**Issue by shassathe** [shassathe/covid_qPCR_test#23]
Color options in the update existing records according to the lab performing them

"Update RNA Extraction Plate Barcode" == Knight Lab
"Update 384 Well Arrayed Plate Barcode" == Knight Lab

Update qPCR Reaction Plate == Laurent Lab
Upload qPCR Results == Laurent Lab

**Comment by ckmah** [comment]
add color legend to navbar

**Comment by shassathe** [comment]
fixed
