### ISSUE TITLE
update database with data fields

### ISSUE THREAD

**Issue by ckmah** [shassathe/covid_qPCR_test#3]
See google sheet: https://docs.google.com/spreadsheets/d/1ufk1zFrBMLIGJzjBdf99DHLO-atWSk6RjpB2XG-HnpM/edit?usp=sharing

- encompasses #2

**Comment by shassathe** [comment]
Disregard the previous google sheet.
Follow this document :  https://docs.google.com/spreadsheets/d/19coxloaTZhGXb_GsEFDcxoJqqLRuafMVF0a6Gad5fSs/edit#gid=0

This document has been shared with Rady's folks as well

**Comment by shassathe** [comment]
All fields in this document have been included.
Closing this
