### ISSUE TITLE
End plate should prompt for plate if > 0 sample barcodes scanned

### ISSUE THREAD

**Issue by ckmah** [shassathe/covid_qPCR_test#30]
@shassathe Please confirm.

**Comment by shassathe** [comment]
Not sure I follow what this bug is

**Comment by ckmah** [comment]
the app should allow for partially filled plates e.g. when some samples are loaded and the "End Plate" button is pressed, prompt for plate barcode.
![image](https://user-images.githubusercontent.com/3103744/79012080-5265f080-7b1a-11ea-95be-5247021e2ada.png)

**Comment by shassathe** [comment]
oh yeah, fixed as well in the latest push to master
closing..
