### ISSUE TITLE
qPCR results get uploaded regardless of correct plat ID

### ISSUE THREAD

**Issue by shassathe** [shassathe/covid_qPCR_test#31]
qPCR file name must match an existing plate ID

**Comment by shassathe** [comment]
@noor01 can you take a look at this as well since you are working with qPCR uploads
Search against the qpcr plate id in the past 48 hours

**Comment by noor01** [comment]
Fixed with ac67fe73bb4bcd5c09ae4bf4c4da406d71d2b878
Also prevent overwriting of existing records.
