### ISSUE TITLE
Update records with fake names from within CRON job

### ISSUE THREAD

**Issue by shassathe** [shassathe/covid_qPCR_test#4]
Include the utility within the to update records with the fake names. Use the sample barcode (field name : barcode) from each record and update django records with the corresponding fake name. I assume we will have a csv or tab-separated file with the barcodes and fake names as the two columns

**Comment by ckmah** [comment]
i can take care of this

**Comment by noor01** [comment]
@ckmah I was just told that they'll give us a csv file with the columns: barcode, first name, last name (all of the names of course are the fake ones). We could just save the csv file on TSCC and call on it during the cron job?

**Comment by shassathe** [comment]
Yes please ! that's what I was hoping for

**Comment by noor01** [comment]
Added functionality to cron job but still waiting for actual csv file from Knight lab. Will close upon receipt of file

**Comment by noor01** [comment]
Updating fake names as part of qpcr upload process instead of cron jobs. Solved with f251d5f8719c301ca25546b2e240308bbc765d11
