### ISSUE TITLE
add feature to review samples

### ISSUE THREAD

**Issue by ckmah** [shassathe/covid_qPCR_test#43]
allow edit `final_results` column

see `sample_result_choices` for `(display, db_value)` pairs

**Comment by ckmah** [comment]
separate tab under `update_existing_records`

**Comment by ckmah** [comment]
@shassathe think i need help with this one

**Comment by shassathe** [comment]
@ckmah is think in the latest push ?

**Comment by ckmah** [comment]
yes `review_results.html` submits list of `final_results` column values as `{'row0': 'Positive', 'row1': 'negative'}` etc.

`views.py index()` needs to query appropriate db entries somehow to update

**Comment by shassathe** [comment]
ok, I'll take a look

**Comment by shassathe** [comment]
fixed in 5678f43
