### ISSUE TITLE
platemap errors after scanning first barcode with dictionary error

### ISSUE THREAD

**Issue by shassathe** [shassathe/covid_qPCR_test#47]
Platemap errors out with message "dict objects is not reversible"

I think this a python error where the dictionaries cannot be reversed. Would work in python 3.8 though

**Comment by shassathe** [comment]
partial fix in df3a911
got rid of the reversed tag
the barcodes are clearly visible on the side, no need to display them in a reverse order any more
@mragsac  close ?

**Comment by ckmah** [comment]
i got this

**Comment by shassathe** [comment]
are you running python 3.8 ? also checkout the fix for displaying barcodes instead of wells.. I posted in my latest commit
