### ISSUE TITLE
Sample Release Column

### ISSUE THREAD

**Issue by shassathe** [shassathe/covid_qPCR_test#6]
Add another column to store sample release status.

Release = sent back to Rady's

Need to confirm what release means for negative samples

**Comment by noor01** [comment]
I think we release all the results back to Rady's Red Cap upon confirmation from the tech regardless of negative, positive, or inconclusive status? It's just a manual check

**Comment by shassathe** [comment]
ok, let's leave this open until we have confirmed. I don't think that we can send the inconclusive test right away. They may choose to repeat the experiment ?

**Comment by shassathe** [comment]
Also, this column does not track if the results were sent to Rady's REDCap. This will track if the actual RNA samples was sent to RAdy's for further positive testing

**Comment by shassathe** [comment]
Added to DB columns. Need to add a way for user to update this status
