### ISSUE TITLE
validations branch: No way to add just one or two rna extraction plates for conversion to rwp like before

### ISSUE THREAD

**Issue by noor01** [shassathe/covid_qPCR_test#67]
Can't duplicate REPs but must also fill all fields. Need some workaround (like before) that allows for one or two REP plates to be added instead of all four.

**Comment by noor01** [comment]
Still giving error when using just one REP. Throws error "Duplicated RNA elution plate IDs not allowed.”

**Comment by ckmah** [comment]
for myself:
change `len == 4` to `len(codes without empty strings) == len(set(codes without empty strings))`
